storage:
  cold_storage:
    raw_zip:
      type: zip
      folders:
        - /home/GP/dataset/collect/cold_storage

dataset:
  pre-processed:
    raw_zip_list:
      type: txt-list
      log:  "logs/pre-processed/raw_zip_list.log"
      file: "blob/dataset/pre-processed/raw_zip_list.txt"
    
    unzip_to_json:
      type:       json
      status:     "blob/status/unzip_to_json.json"
      log:        "logs/pre-processed/unzip_to_json.log"
      folder:     "blob/dataset/pre-processed/unzip_to_json"

    h5:
      file: "blob/dataset/pre-processed/h5/traffic_features.h5"
      log: "logs/create_h5_file.log"
      selected_vdids: null
      time_range: null
      overwrite: false

# Model training configuration
training:
  single_vd:
    experiment_dir: "blob/experiments/single_vd_without_social_pooling"
    log: "logs/train_single_vd_without_social_pooling.log"
    epochs: 5
    batch_size: 1
    sequence_length: 5
    model_type: "lstm"
  
  multi_vd:
    experiment_dir: "blob/experiments/multi_vd_without_social_pooling"
    log: "logs/train_multi_vd_without_social_pooling.log"
    epochs: 5
    batch_size: 1
    sequence_length: 5
    num_vds: 1
    model_type: "lstm"
  
  independent_multi_vd:
    experiment_dir: "blob/experiments/independent_multi_vd_without_social_pooling"
    log: "logs/train_independent_multi_vd_without_social_pooling.log"
    epochs: 5
    batch_size: 1
    sequence_length: 5
    num_vds: 1
    target_vd_index: 0
    model_type: "lstm"