configs:
  - cfgs/data/standard.yaml
  - cfgs/models/xlstm.yaml
  - cfgs/social_pooling/st_attention.yaml
  - cfgs/training/standard.yaml
  - cfgs/datasets/pems_bay/standard.yaml

# Profile-specific overrides
overrides:
  data:
    stride: 3  
    path: "blob/dataset/processed/pems_bay.h5"
    fill_missing: interpolate
    loader:
      batch_size: 64
      num_workers: 8

    selected_vdids:
        - "400201"
        - "400274"
        - "400581" 
        - "400687"
        - "400794"
        - "401351"
        - "401891"
        - "402365"
        - "404586"
        - "413845"
  trainer:
    max_epochs: 20
    num_sanity_val_steps: 0
  optimizer:
    lr: 0.001
