configs:
  - cfgs/data/standard.yaml
  - cfgs/models/xlstm.yaml
  - cfgs/social_pooling/spatial_basic.yaml
  - cfgs/training/standard.yaml
  - cfgs/datasets/pems_bay/standard.yaml

# Profile-specific overrides
overrides:
  data:
    path: "blob/dataset/processed/pems_bay.h5"
    loader:
      batch_size: 32

    selected_vdids:
        - "400201"
        - "400274"
        - "400581" 
        - "400687"
        - "400794"
        - "401351"
        - "401891"
        - "402365"
        - "404586"
        - "413845"
  trainer:
    max_epochs: 10