# PEMS-BAY Development Profile
# Combines modular configurations for PEMS-BAY dataset training

configs:
  - cfgs/data/dev.yaml
  - cfgs/models/xlstm.yaml
  - cfgs/social_pooling/spatial_basic.yaml
  - cfgs/training/dev.yaml
  - cfgs/datasets/pems_bay.yaml

# Profile-specific overrides
overrides:
  data:
    # Use converted PEMS-BAY HDF5 file
    path: "blob/dataset/processed/pems_bay.h5"
    
    # PEMS-BAY specific data parameters
    selected_features: ["avg_speed", "lanes", "length", "latitude", "longitude", "direction"]
    
    # Adjust batch size for 6 features
    loader:
      batch_size: 16  # Reduced from 8 to handle larger feature set