# PEMS-BAY Development Profile
# Combines modular configurations for PEMS-BAY dataset training

configs:
  - cfgs/data/standard.yaml
  - cfgs/models/xlstm.yaml
  - cfgs/social_pooling/st_attention_basic.yaml
  - cfgs/training/standard.yaml
  - cfgs/datasets/metr_la/standard.yaml

# Profile-specific overrides
overrides:
  data:
    stride: 10 
    path: "blob/dataset/processed/metr_la.h5"
    
    # Adjust batch size for 6 features
    loader:
      batch_size: 32  # Reduced from 8 to handle larger feature set
