# Social-xLSTM Project Configuration File
# This file contains all configuration parameters for the data processing pipeline and model training
# All paths are relative to the project root directory

# Storage configuration for raw data sources
storage:
  cold_storage:
    raw_zip:
      type: zip  # File type: zip archives containing traffic XML data
      folders:   # List of directories containing raw ZIP files
        - /home/GP/dataset/collect/cold_storage

# Dataset preprocessing pipeline configuration
dataset:
  pre-processed:
    # Step 1: List all ZIP files from the source directories
    raw_zip_list:
      type: txt-list  # Output format: text file with one ZIP path per line
      log:  "logs/default/pre-processed/raw_zip_list.log"  # Log file for this step
      file: "blob/dataset/pre-processed/raw_zip_list.txt"  # Output file containing ZIP list
    
    # Step 2: Extract ZIP files and convert XML to JSON format
    unzip_to_json:
      type:       json  # Output format: JSON files
      status:     "blob/status/default_unzip_to_json.json"  # Status tracking file for extraction progress
      log:        "logs/default/pre-processed/unzip_to_json.log"  # Log file for extraction process
      folder:     "blob/dataset/pre-processed/unzip_to_json"  # Output directory for JSON files

    # Step 3: Create HDF5 dataset from JSON files - Production dataset with sufficient data
    h5:
      file: "blob/dataset/pre-processed/h5/traffic_features_default.h5"  # Output HDF5 file path
      log: "logs/default/create_h5_file.log"  # Log file for HDF5 creation
      selected_vdids: ["VD-28-0740-000-001", "VD-11-0020-008-001", "VD-13-0660-000-002"]  # Production VDs - Valid data
      time_range: "2025-03-18_00-00-00 2025-03-20_23-59-59"  # 3 days for production experiments
      overwrite: true      # Overwrite existing file for fresh data
    
    # Alternative stable dataset for overfitting validation  
    h5_stable:
      file: "blob/dataset/pre-processed/h5/traffic_features_stable.h5"  # Stable dataset path
      log: "logs/default/create_h5_stable_file.log"  # Log file for stable HDF5 creation
      selected_vdids: ["VD-28-0740-000-001", "VD-11-0020-008-001", "VD-13-0660-000-002"]  # Same VDs as main
      time_range: "2025-03-18_00-00-00 2025-03-20_23-59-59"  # Same time range
      overwrite: true      # Overwrite existing file for fresh data

# Model training configuration - Production training with default prefix
training_lstm:
  # Single VD training configuration (no spatial relationships)
  single_vd:
    experiment_dir: "blob/experiments/default/lstm/single_vd"  # Output directory for experiment results
    log: "logs/default/train_single_vd_lstm.log"  # Training log file
    epochs: 200          # Sufficient for convergence
    batch_size: 32      # Optimized for RTX 3090 Ti (24GB VRAM)
    sequence_length: 20  # Longer sequences for better temporal modeling
    model_type: "lstm"  # Model architecture: "lstm" or "xlstm"
    select_vd_id: "VD-28-0740-000-001"  # VD with 98.3% valid data
    # Optimized training parameters from fixed configs
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  
  # Multi-VD training configuration (processes multiple VDs independently)
  multi_vd:
    experiment_dir: "blob/experiments/default/lstm/multi_vd"  # Output directory for experiment results
    log: "logs/default/train_multi_vd_lstm.log"  # Training log file
    epochs: 200          # More epochs for production
    batch_size: 32       # Optimized for RTX 3090 Ti (24GB VRAM)
    sequence_length: 20  # Longer sequences for better temporal modeling
    num_vds: 50         # Train on first 50 VDs (reasonable subset)
    # Alternative: use specific VD IDs with vd_ids parameter
    # vd_ids: "VD-28-0740-000-001,VD-11-0020-008-001,VD-13-0660-000-002"  # Valid VDs with high data quality
    model_type: "lstm"  # Model architecture: "lstm" or "xlstm"
    # Optimized training parameters from fixed configs
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  
  # Independent multi-VD training (uses multiple VDs as input, predicts single target VD)
  independent_multi_vd:
    experiment_dir: "blob/experiments/default/lstm/independent_multi_vd"  # Output directory
    log: "logs/default/train_independent_multi_vd_lstm.log"  # Training log file
    epochs: 200          # More epochs for production
    batch_size: 32       # Optimized for RTX 3090 Ti (24GB VRAM)
    sequence_length: 20  # Longer sequences for better temporal modeling
    num_vds: 50         # Train on first 50 VDs (reasonable subset)
    # Alternative: use specific VD IDs with vd_ids parameter
    # vd_ids: "VD-28-0740-000-001,VD-11-0020-008-001,VD-13-0660-000-002"  # Valid VDs with high data quality
    target_vd_index: 0  # Index of the VD to predict (0-based)
    model_type: "lstm"  # Model architecture: "lstm" or "xlstm"
    # Optimized training parameters from fixed configs
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard

# xLSTM Training Configuration - Extended LSTM experiments for production
training_xlstm:
  # Single VD xLSTM training
  single_vd:
    experiment_dir: "blob/experiments/default/xlstm/single_vd"
    log: "logs/default/train_single_vd_xlstm.log"
    epochs: 200          # More epochs for production
    batch_size: 32       # Optimized for RTX 3090 Ti (24GB VRAM)
    sequence_length: 20  # Same as LSTM for fair comparison
    model_type: "xlstm"
    select_vd_id: "VD-28-0740-000-001"  # VD with 98.3% valid data
    # xLSTM specific parameters - production settings
    embedding_dim: 128
    num_blocks: 6
    slstm_at: [1, 3]
    context_length: 256
    dropout: 0.1
    backend: "vanilla"
    # Optimized training parameters from fixed configs
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  
  # Multi-VD xLSTM training
  multi_vd:
    experiment_dir: "blob/experiments/default/xlstm/multi_vd"
    log: "logs/default/train_multi_vd_xlstm.log"
    epochs: 200          # More epochs for production
    batch_size: 32       # Optimized for RTX 3090 Ti (24GB VRAM)
    sequence_length: 20  # Same as LSTM for fair comparison
    model_type: "xlstm"
    num_vds: 50         # Train on first 50 VDs (reasonable subset)
    # Alternative: use specific VD IDs with vd_ids parameter
    # vd_ids: "VD-28-0740-000-001,VD-11-0020-008-001,VD-13-0660-000-002"  # Valid VDs with high data quality
    # xLSTM specific parameters - production settings
    embedding_dim: 128
    num_blocks: 6
    slstm_at: [1, 3]
    context_length: 256
    dropout: 0.1
    backend: "vanilla"
    # Optimized training parameters from fixed configs
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard