# Social-xLSTM Development/Testing Configuration
# Optimized for fast development and testing with small datasets

# Storage configuration - same as production
storage:
  cold_storage:
    raw_zip:
      type: zip
      folders:
        - /home/GP/dataset/collect/cold_storage

# Dataset preprocessing - optimized for development
dataset:
  pre-processed:
    raw_zip_list:
      type: txt-list
      log:  "logs/dev/pre-processed/raw_zip_list.log"
      file: "blob/dataset/pre-processed/raw_zip_list.txt"
    
    unzip_to_json:
      type:       json
      status:     "blob/status/dev_unzip_to_json.json"
      log:        "logs/dev/pre-processed/unzip_to_json.log"
      folder:     "blob/dataset/pre-processed/unzip_to_json"

    # Development dataset with sufficient data for validation/test splits
    h5:
      file: "blob/dataset/pre-processed/h5/traffic_features_dev.h5"
      log: "logs/dev/create_h5_file.log"
      selected_vdids: ["VD-11-0020-002-002", "VD-28-0740-000-001", "VD-13-0660-000-002"]
      time_range: "2025-03-18_00-49-00,2025-03-18_05-00-00"  # About 4 hours to enable validation/test splits
      overwrite: true

# Development training configuration - fast and lightweight
training_lstm:
  single_vd:
    experiment_dir: "blob/experiments/dev/lstm/single_vd"
    log: "logs/dev/train_single_vd_lstm.log"
    epochs: 10          # More epochs to show training curves
    batch_size: 4       # Small batches
    sequence_length: 5
    model_type: "lstm"
    select_vd_id: "VD-11-0020-002-002"
  
  multi_vd:
    experiment_dir: "blob/experiments/dev/lstm/multi_vd"
    log: "logs/dev/train_multi_vd_lstm.log"
    epochs: 10          # More epochs to show training curves
    batch_size: 4
    sequence_length: 5
    num_vds: 3          # All 3 VDs in dev dataset
    model_type: "lstm"
  
  independent_multi_vd:
    experiment_dir: "blob/experiments/dev/lstm/independent_multi_vd"
    log: "logs/dev/train_independent_multi_vd_lstm.log"
    epochs: 10          # More epochs to show training curves
    batch_size: 4
    sequence_length: 5
    num_vds: 3
    target_vd_index: 0
    model_type: "lstm"

# xLSTM Training Configuration - Extended LSTM experiments
training_xlstm:
  single_vd:
    experiment_dir: "blob/experiments/dev/xlstm/single_vd"
    log: "logs/dev/train_single_vd_xlstm.log"
    epochs: 10
    batch_size: 4
    sequence_length: 5
    model_type: "xlstm"
    select_vd_id: "VD-11-0020-002-002"
    # xLSTM specific parameters
    embedding_dim: 64
    num_blocks: 4
    slstm_at: [1, 3]
    context_length: 256
    dropout: 0.1
    backend: "vanilla"
  
  multi_vd:
    experiment_dir: "blob/experiments/dev/xlstm/multi_vd"
    log: "logs/dev/train_multi_vd_xlstm.log"
    epochs: 10
    batch_size: 4
    sequence_length: 5
    model_type: "xlstm"
    num_vds: 3
    # xLSTM specific parameters
    embedding_dim: 64
    num_blocks: 4
    slstm_at: [1, 3]
    context_length: 256
    dropout: 0.1
    backend: "vanilla"