storage:
  cold_storage:
    raw_zip:
      type: zip
      folders:
      - /home/GP/dataset/collect/cold_storage
dataset:
  pre-processed:
    raw_zip_list:
      type: txt-list
      log: logs/dev/pre-processed/raw_zip_list.log
      file: blob/dataset/pre-processed/raw_zip_list.txt
    unzip_to_json:
      type: json
      status: blob/status/dev_unzip_to_json.json
      log: logs/dev/pre-processed/unzip_to_json.log
      folder: blob/dataset/pre-processed/unzip_to_json
    h5:
      file: blob/dataset/pre-processed/h5/traffic_features_expanded.h5
      log: logs/dev/create_h5_file.log
      selected_vdids:
      - VD-28-0740-000-001
      - VD-11-0020-008-001
      - VD-13-0660-000-002
      time_range: 2025-03-18_00-00-00,2025-04-18_00-00-00
      overwrite: true
    # Alternative stable dataset for overfitting validation
    h5_stable:
      file: blob/dataset/pre-processed/h5/traffic_features_stable.h5
      log: logs/dev/create_h5_stable_file.log
      selected_vdids:
      - VD-28-0740-000-001
      - VD-11-0020-008-001
      - VD-13-0660-000-002
      time_range: 2025-03-18_00-00-00,2025-04-18_00-00-00
      overwrite: true
training_lstm:
  single_vd:
    experiment_dir: blob/experiments/dev/lstm/single_vd
    log: logs/dev/train_single_vd_lstm.log
    epochs: 50
    batch_size: 16
    sequence_length: 5
    model_type: lstm
    select_vd_id: VD-28-0740-000-001
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    # Optimized training parameters from fixed configs
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  multi_vd:
    experiment_dir: blob/experiments/dev/lstm/multi_vd
    log: logs/dev/train_multi_vd_lstm.log
    epochs: 50
    batch_size: 16
    sequence_length: 5
    num_vds: 3
    model_type: lstm
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    # Optimized training parameters from fixed configs
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  independent_multi_vd:
    experiment_dir: blob/experiments/dev/lstm/independent_multi_vd
    log: logs/dev/train_independent_multi_vd_lstm.log
    epochs: 50
    batch_size: 16
    sequence_length: 5
    num_vds: 3
    target_vd_index: 0
    model_type: lstm
    hidden_size: 32
    num_layers: 1
    dropout: 0.5
    learning_rate: 0.0005
    weight_decay: 0.01
    # Optimized training parameters from fixed configs
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
training_xlstm:
  single_vd:
    experiment_dir: blob/experiments/dev/xlstm/single_vd
    log: logs/dev/train_single_vd_xlstm.log
    epochs: 10
    batch_size: 4
    sequence_length: 5
    model_type: xlstm
    select_vd_id: VD-28-0740-000-001
    embedding_dim: 64
    num_blocks: 4
    slstm_at:
    - 1
    - 3
    context_length: 256
    dropout: 0.1
    backend: vanilla
    # Optimized training parameters from fixed configs
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
  multi_vd:
    experiment_dir: blob/experiments/dev/xlstm/multi_vd
    log: logs/dev/train_multi_vd_xlstm.log
    epochs: 10
    batch_size: 4
    sequence_length: 5
    model_type: xlstm
    num_vds: 3
    embedding_dim: 64
    num_blocks: 4
    slstm_at:
    - 1
    - 3
    context_length: 256
    dropout: 0.1
    backend: vanilla
    # Optimized training parameters from fixed configs
    learning_rate: 0.0005
    weight_decay: 0.01
    early_stopping_patience: 8
    gradient_clip_value: 0.5
    use_scheduler: true
    scheduler_patience: 5
    # Dataset parameters
    prediction_length: 1
    train_ratio: 0.8
    val_ratio: 0.2
    test_ratio: 0.0
    normalize: true
    normalization_method: standard
